Docs 4.2 migration
GluuFederation/docs-gluu-server-prod pull request #141
Opened 2023-12-30 11:32 UTC by misba7

2024-01-01 03:19 UTC, iromli requested changes

2024-01-01 03:19 UTC, iromli commented on docs/source/upgrade/ldap-migration.md
> +1.  Run `helm upgrade`.
Provide example of full command, please.

2024-01-01 03:19 UTC, iromli commented on docs/source/upgrade/ldap-migration.md
> +1.  Run `helm upgrade`.
Provide example of full command.

2024-01-01 22:14 UTC, moabu approved these changes

2024-01-01 22:16 UTC, moabu requested changes
Regarding the known upgrade issue due to api spec changes .we should detail that the user should rerun the helm upgrade command again so that it’s registered with the helm lifecycle that the upgrade was successful . That should be in the steps

2024-01-02 01:54 UTC, iromli requested changes

2024-01-02 01:54 UTC, iromli commented on docs/source/upgrade/ldap-migration.md
> +      upgrade:
The newest image `gluufederation/upgrade:4.5.3-2` has been released. The YAML should reflect this new image.

2024-01-02 06:27 UTC, moabu requested changes

2024-01-02 06:27 UTC, moabu commented on docs/source/upgrade/ldap-migration.md
> +This documentation demonstrates how to upgrade from CN 4.2 LDAP to 4.5 PostgreSQL.
We can say >= 4.2 LDAP to 4.5 postgres. Apply this notion across the doc because this will work for versions 4.3 as well.

2024-01-03 17:45 UTC, iromli requested changes

2024-01-03 17:45 UTC, iromli commented on docs/source/upgrade/ldap-migration.md
> +              image: gluufederation/persistence:4.5.3_dev
Please change `dev` to latest stable image.

2024-01-03 18:15 UTC, iromli commented on docs/source/upgrade/ldap-migration.md
> +              image: gluufederation/persistence:4.5.3_dev
The latest version is `gluufederation/persistence:4.5.3-2`

2024-01-08 05:34 UTC, iromli approved these changes

2024-01-08 07:41 UTC, moabu approved these changes

2024-01-08 07:41 UTC, merged